# Text shown on the index page.
index_title: Våra samlade recept
index_description:
  Po-tay-toes. Boil 'em, mash 'em, stick 'em in a stew. Lovely big golden chips
  with a nice piece of fried fish. Even you couldn't say no to that...

# Whether to show each recipe's image, if available, on the index page. To
# enable, set this option to any non-empty value (other than "false" in recent
# versions of Pandoc). To disable, keep it blank.
show_images_on_index: true

# You can change the content language (really only relevant for hyphenation)
# and related textual labels here.
lang: se
strings:
  search_placeholder: Sök...
  uncategorized_label: Okategoriserad
  source_label: Källa
  vegan_label: Vegan
  meat_label: Kött/Fisk
  spicy_label: Spicy
  sweet_label: Sötsaker
  salty_label: Salt
  sour_label: Sur
  bitter_label: Bitter
  umami_label: Umami
  footer_text: Tada!
  updated_on: Senast uppdaterad
  edit: Editera

# If you maintain your recipes in a GitHub repository, you can specify its URL
# here – if non-empty, an "Edit" link will be shown at the bottom of each recipe
# page, referring you to the corresponding Markdown file on GitHub. If you've
# got some sort of continous integration (like the included GitHub Action) set
# up, this effectively turns your site into a wiki.
github_url: 

# Remote for deployment – the value of this setting will be passed to rsync as a
# destination, so you probably want it to look like USER@SERVER:PATH. Make sure
# it's correct – the path in particular – since otherwise stuff that shouldn't
# be deleted or overwritten might indeed be deleted or overwritten!
deploy_remote:
